# Generated by Django 5.2.8 on 2025-11-15 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preflight',
            fields=[
                ('flight_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('filed_by', models.CharField(blank=True, max_length=100)),
                ('filing_time', models.CharField(blank=True, max_length=100)),
                ('departure_location', models.CharField(blank=True, max_length=100)),
                ('departure_time', models.CharField(blank=True, max_length=100)),
                ('arrival_location', models.CharField(blank=True, max_length=100)),
                ('est_arrival_time', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('preflight', models.ForeignKey(db_column='flight_number', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.preflight')),
            ],
        ),
    ]
